### ISSUE TITLE
Constant WP_POST_REVISIONS is already defined in wp-config.php file

### ISSUE THREAD

**Issue by gibbywilson** [rrodrigonuez/WP-Revisions-Limit#1]
I get this message

Constant WP_POST_REVISIONS is already defined in wp-config.php file, remove it to be able to set up a limit for your post revisions.

In the file it is 1

What does the 1 mean ? It saves only one revision? If so do I need the plugin ?

Thanks

**Comment by rrodrigonuez** [comment]
Hi gibbywilson,

some how you already had defined the maximum number of revisions stored for your WordPress site, and this is defined in your wp-config.php file.

If you want to use this plugin in order be able to introduce a number to limit the number of revisions, you will need to remove the line that starts with define( 'WP_POST_REVISIONS', .....); in your wp-config.php file.
Once you have done that, everything will work perfectly.

Thanks!
